import { pbkdf2Sync, randomBytes } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ITERATIONS = 200_000
const SALT_BYTES = 16
const KEY_BYTES = 32

const raw = process.argv[2]
if (!raw || typeof raw !== 'string') {
  console.error('Usage: npm run gate:set "<password|passphrase>"')
  process.exit(1)
}

const password = raw.normalize('NFC')
if (password.length < 6) {
  console.warn(`[warn] passphrase is ${password.length} chars — short. Continuing.`)
}

const salt = randomBytes(SALT_BYTES)
const hash = pbkdf2Sync(Buffer.from(password, 'utf8'), salt, ITERATIONS, KEY_BYTES, 'sha256')

const SALT_B64 = salt.toString('base64')
const HASH_B64 = hash.toString('base64')

const out = `// AUTO-GENERATED by scripts/gate-set.mjs — do not edit by hand.
// Regenerate with: npm run gate:set "<password>"
//
// THREAT MODEL: this is a "soft" gate — soft privacy only, not real auth — see README.
// The salt + hash are committed in the source bundle. A determined attacker with the
// bundle CAN brute-force the password offline (PBKDF2 200k iterations slows them, but
// the contents — once revealed — are still in plain bytes in the same bundle).
// For real privacy, use the AES-GCM upgrade path documented in PRIV-01 (v2 roadmap).

export const SALT_B64 = ${JSON.stringify(SALT_B64)}
export const HASH_B64 = ${JSON.stringify(HASH_B64)}
export const ITERATIONS = ${ITERATIONS}
`

const outPath = resolve(process.cwd(), 'src/gate.config.ts')
writeFileSync(outPath, out)
console.log(
  `gate.config.ts written (salt: ${SALT_BYTES}B, hash: ${KEY_BYTES}B base64, iterations: ${ITERATIONS}).`,
)
