/**
 * Vite plugin that resolves the `virtual:poems` module (Phase 2, CONT-01).
 *
 * Pipeline:
 *   - resolveId('virtual:poems')  → '\0virtual:poems'
 *   - load(...)                    → calls loadManifest() (Plan 02-01) and emits
 *                                    a TypeScript module string with `poems`
 *                                    array + helpers `getPoem/getNextPoem/getPrevPoem`.
 *   - configureServer              → hooks into server.watcher to add explicit
 *                                    watches on poems.txt, manifest.yaml, and
 *                                    public/photos/ (so add/remove/rename
 *                                    triggers HMR even on files not yet
 *                                    referenced in the dep graph).
 *   - handleHotUpdate              → invalidates the virtual module + sends
 *                                    `full-reload` when any watched path changes.
 *
 * Errors during dev: returns a module that throws at runtime, so Vite shows the
 * error overlay instead of crashing the dev server. In build mode: rethrows so
 * the build aborts (D-06 — build-time validation gate).
 */
import path from 'node:path'
import type { Plugin, ViteDevServer } from 'vite'
import { loadManifest, ManifestValidationError } from './manifest-loader'
import type { Poem } from './poem-schema'

const VIRTUAL_ID = 'virtual:poems'
const RESOLVED_ID = '\0' + VIRTUAL_ID

export interface PoemsPluginOptions {
  /** Repository root. Defaults to `process.cwd()`. */
  rootDir?: string
}

export function poemsPlugin(opts: PoemsPluginOptions = {}): Plugin {
  const rootDir = opts.rootDir ?? process.cwd()
  const poemsTxt = path.join(rootDir, 'poems.txt')
  const manifestYaml = path.join(rootDir, 'content', 'manifest.yaml')
  const photosDir = path.join(rootDir, 'public', 'photos')

  let server: ViteDevServer | undefined
  let isBuild = false

  return {
    name: 'lulu:poems',

    configResolved(config) {
      isBuild = config.command === 'build'
    },

    resolveId(id: string): string | undefined {
      if (id === VIRTUAL_ID) return RESOLVED_ID
      return undefined
    },

    load(id: string): string | undefined {
      if (id !== RESOLVED_ID) return undefined

      try {
        const { poems, watchPaths } = loadManifest({ rootDir })
        // Track each watched path in Vite's dep graph so changes invalidate
        // this module. addWatchFile is per-load — must be called every time.
        for (const p of watchPaths) {
          this.addWatchFile(p)
        }
        return generateModuleSource(poems)
      } catch (err: unknown) {
        if (isBuild) {
          // Build mode — fail loudly so CI aborts before producing a broken bundle.
          throw err
        }
        // Dev mode — emit a module that throws at runtime so the error overlay
        // shows the validation message instead of crashing the dev server.
        const message = err instanceof ManifestValidationError ? err.message : err instanceof Error ? err.message : String(err)
        return generateErrorModuleSource(message)
      }
    },

    configureServer(s: ViteDevServer) {
      server = s
      // Watch the photos directory explicitly. addWatchFile() in load() covers
      // existing files in the dep graph, but adding/removing a file inside the
      // directory needs a directory-level watch.
      s.watcher.add(photosDir)
      s.watcher.add(poemsTxt)
      s.watcher.add(manifestYaml)
    },

    handleHotUpdate({ file }) {
      if (!server) return
      const isWatched =
        file === poemsTxt ||
        file === manifestYaml ||
        file.startsWith(photosDir + path.sep) ||
        file === photosDir
      if (!isWatched) return

      const mod = server.moduleGraph.getModuleById(RESOLVED_ID)
      if (mod) {
        server.moduleGraph.invalidateModule(mod)
      }
      // Full reload — consumers (HomeView, PolaroidView) hold poem references
      // at module init, not via reactive refs, so a full reload is the safest
      // way to surface the new content.
      server.ws.send({ type: 'full-reload' })
      return []
    },
  }
}

/** Generates the TS module source for a successfully-loaded manifest. */
function generateModuleSource(poems: Poem[]): string {
  const json = JSON.stringify(poems)
  return `// Generated by vite/plugin-poems.ts — do not edit.
export const poems = ${json}
const bySlug = Object.fromEntries(poems.map((p) => [p.slug, p]))
export function getPoem(slug) {
  return bySlug[slug]
}
export function getNextPoem(slug) {
  const i = poems.findIndex((p) => p.slug === slug)
  if (i < 0) return undefined
  return poems[(i + 1) % poems.length]
}
export function getPrevPoem(slug) {
  const i = poems.findIndex((p) => p.slug === slug)
  if (i < 0) return undefined
  return poems[(i - 1 + poems.length) % poems.length]
}
`
}

/**
 * Dev-mode fallback: emits a module that throws when imported, so the Vite
 * error overlay surfaces the validation message instead of the dev server
 * crashing or serving stale content.
 */
function generateErrorModuleSource(message: string): string {
  const safe = JSON.stringify(message)
  return `// Generated by vite/plugin-poems.ts — manifest validation failed.
const __error = new Error(${safe})
__error.name = 'ManifestValidationError'
throw __error
export const poems = []
export function getPoem() { throw __error }
export function getNextPoem() { throw __error }
export function getPrevPoem() { throw __error }
`
}
