// AUTO-GENERATED by scripts/gate-set.mjs — do not edit by hand.
// Regenerate with: npm run gate:set "<password>"
//
// THREAT MODEL: this is a "soft" gate — soft privacy only, not real auth — see README.
// The salt + hash are committed in the source bundle. A determined attacker with the
// bundle CAN brute-force the password offline (PBKDF2 200k iterations slows them, but
// the contents — once revealed — are still in plain bytes in the same bundle).
// For real privacy, use the AES-GCM upgrade path documented in PRIV-01 (v2 roadmap).

export const SALT_B64 = "IBZRuvpmPXADbnpvolZq9g=="
export const HASH_B64 = "R0BaUK4elX8W7QpNjWxxZYbf4w0NHxvBqnkHUoZ7Sz8="
export const ITERATIONS = 200000
