import { describe, it, expect, beforeEach, afterEach, beforeAll } from 'vitest'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import sharp from 'sharp'
import { poemsPlugin } from '../../vite/plugin-poems'
import { ManifestValidationError } from '../../vite/manifest-loader'

let tmp: string

/** Minimal valid 1x1 JPEG buffer generated by sharp itself. The plugin runs
 *  sharp() on each photo to produce LQIP placeholders (Phase 4), so test
 *  fixtures must be real decodable images. Generating via sharp guarantees
 *  the same library that consumes them accepts them. */
let TINY_JPEG: Buffer
beforeAll(async () => {
  TINY_JPEG = await sharp({
    create: { width: 4, height: 4, channels: 3, background: '#888' },
  })
    .jpeg({ quality: 60 })
    .toBuffer()
})

const REAL_POEMS = `"Un altro sogno" - 22/7/2025 | 17:38

Sarà un altro giorno.

—————

"Luce" - 28/7/2025

Luce di luna.
`

const VALID_YAML = `\
- photo: Un_altro_sogno.JPG
  poem: un-altro-sogno
  alt: "Foto della poesia Un altro sogno"
  rope: 0
  rotation: -2.4
  liftDelay: 0
- photo: Luce.jpg
  poem: luce
  alt: "Foto della poesia Luce di luna"
  rope: 0
  rotation: 1.8
  liftDelay: 80
`

function setupFixture(yaml: string, photos: Array<[string, string]>, poemsTxt = REAL_POEMS): string {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'lulu-plugin-test-'))
  fs.mkdirSync(path.join(tmp, 'content'))
  // Phase 4: photos now live under src/assets/photos/ so vite-imagetools can
  // transform them at build. The legacy public/photos/ path is no longer used.
  fs.mkdirSync(path.join(tmp, 'src', 'assets', 'photos'), { recursive: true })
  fs.writeFileSync(path.join(tmp, 'content', 'manifest.yaml'), yaml)
  fs.writeFileSync(path.join(tmp, 'poems.txt'), poemsTxt)
  for (const [name] of photos) {
    // Phase 4: plugin runs sharp() on the photo to produce LQIP, so the
    // fixture content must be a real (if tiny) JPEG. The original `body`
    // arg is ignored — kept in the tuple for backwards-compat with callers.
    fs.writeFileSync(path.join(tmp, 'src', 'assets', 'photos', name), TINY_JPEG)
  }
  return tmp
}

interface MockCtx {
  addWatchFile: (p: string) => void
  watched: string[]
}

function makeCtx(): MockCtx {
  const watched: string[] = []
  return {
    watched,
    addWatchFile(p: string) {
      watched.push(p)
    },
  }
}

beforeEach(() => {
  tmp = ''
})

afterEach(() => {
  if (tmp && fs.existsSync(tmp)) {
    fs.rmSync(tmp, { recursive: true, force: true })
  }
})

describe('poemsPlugin', () => {
  describe('resolveId', () => {
    it("resolves 'virtual:poems' to '\\0virtual:poems'", () => {
      const plugin = poemsPlugin({ rootDir: process.cwd() })
      const resolveId = plugin.resolveId as (this: unknown, id: string) => string | undefined
      expect(resolveId.call({}, 'virtual:poems')).toBe('\0virtual:poems')
    })

    it('returns undefined for other ids', () => {
      const plugin = poemsPlugin({ rootDir: process.cwd() })
      const resolveId = plugin.resolveId as (this: unknown, id: string) => string | undefined
      expect(resolveId.call({}, 'something-else')).toBeUndefined()
      expect(resolveId.call({}, 'vue')).toBeUndefined()
    })
  })

  describe('load', () => {
    it("returns undefined for non-virtual ids", async () => {
      const plugin = poemsPlugin({ rootDir: process.cwd() })
      const ctx = makeCtx()
      const load = plugin.load as (this: unknown, id: string) => Promise<string | undefined>
      // Phase 4: load() is async; for non-virtual ids the awaited result
      // resolves to undefined.
      const result = await load.call(ctx, 'some-real-file.ts')
      expect(result).toBeUndefined()
    })

    it("emits a TS module string with poems array + helpers when manifest is valid", async () => {
      const root = setupFixture(VALID_YAML, [
        ['Un_altro_sogno.JPG', 'x'],
        ['Luce.jpg', 'y'],
      ])
      const plugin = poemsPlugin({ rootDir: root })
      const ctx = makeCtx()
      const load = plugin.load as (this: MockCtx, id: string) => Promise<string>
      const out = await load.call(ctx, '\0virtual:poems')

      expect(out).toContain('export const poems')
      expect(out).toContain('un-altro-sogno')
      expect(out).toContain('luce')
      expect(out).toContain('getPoem')
      expect(out).toContain('getNextPoem')
      expect(out).toContain('getPrevPoem')
    })

    it("registers watch files (FILES only, not directories) via addWatchFile during load", async () => {
      const root = setupFixture(VALID_YAML, [
        ['Un_altro_sogno.JPG', 'x'],
        ['Luce.jpg', 'y'],
      ])
      const plugin = poemsPlugin({ rootDir: root })
      const ctx = makeCtx()
      const load = plugin.load as (this: MockCtx, id: string) => Promise<string>
      await load.call(ctx, '\0virtual:poems')

      expect(ctx.watched).toContain(path.join(root, 'poems.txt'))
      expect(ctx.watched).toContain(path.join(root, 'content', 'manifest.yaml'))
      // The photos directory is NOT registered via addWatchFile — Vite would
      // try to resolve it as a module import. Directory watching is done via
      // server.watcher.add() in configureServer instead.
      expect(ctx.watched).not.toContain(path.join(root, 'src', 'assets', 'photos'))
    })

    it("throws ManifestValidationError in build mode when fixture manifest is invalid", async () => {
      // YAML references Un_altro_sogno.JPG but disk only has Luce.jpg → orphan + missing
      const root = setupFixture(VALID_YAML, [['Luce.jpg', 'y']])
      const plugin = poemsPlugin({ rootDir: root })
      // Simulate `configResolved` with build command so plugin enters strict mode.
      const configResolved = plugin.configResolved as (this: unknown, cfg: { command: 'build' | 'serve' }) => void
      configResolved.call({}, { command: 'build' })
      const ctx = makeCtx()
      const load = plugin.load as (this: MockCtx, id: string) => Promise<string>
      await expect(load.call(ctx, '\0virtual:poems')).rejects.toThrow(ManifestValidationError)
    })

    it("emits an error-throwing module in dev mode when fixture manifest is invalid", async () => {
      const root = setupFixture(VALID_YAML, [['Luce.jpg', 'y']])
      const plugin = poemsPlugin({ rootDir: root })
      // Default = dev mode (no configResolved call, isBuild stays false).
      const ctx = makeCtx()
      const load = plugin.load as (this: MockCtx, id: string) => Promise<string>
      const out = await load.call(ctx, '\0virtual:poems')
      // Module is generated, contains a throw, and includes the validation message.
      expect(out).toContain('throw __error')
      expect(out).toMatch(/Manifest invalido/)
    })
  })

  describe('plugin shape', () => {
    it("has the expected name and HMR hooks", () => {
      const plugin = poemsPlugin({ rootDir: process.cwd() })
      expect(plugin.name).toBe('lulu:poems')
      expect(typeof plugin.resolveId).toBe('function')
      expect(typeof plugin.load).toBe('function')
      expect(typeof plugin.handleHotUpdate).toBe('function')
      expect(typeof plugin.configureServer).toBe('function')
    })
  })
})
